const PostEditorTheme = {
  paragraph: 'editor-paragraph',
  heading: {
    h1: 'editor-h1',
    h2: 'editor-h2',
    h3: 'editor-h3',
  },
  list: {
    ul: 'editor-list-ul',
    ol: 'editor-list-ol',
    listitem: 'editor-listitem',
    nested: {
      listitem: 'editor-nested-listitem',
    },
  },
  code: 'editor-code',
  codeHighlight: {
    atrule: 'token atrule',
    attr: 'token attr',
    boolean: 'token boolean',
    builtin: 'token builtin',
    cdata: 'token cdata',
    char: 'token char',
    class: 'token class-name',
    'class-name': 'token class-name',
    constant: 'token constant',
    function: 'token function',
    keyword: 'token keyword',
    operator: 'token operator',
    property: 'token property',
    prolog: 'token prolog',
    punctuation: 'token punctuation',
    string: 'token string',
    comment: 'token comment',
    number: 'token number',
    regex: 'token regex',
    selector: 'token selector',
    tag: 'token tag',
    url: 'token url',
    variable: 'token variable',
    decorator: 'token decorator',
    annotation: 'token decorator',
  },
  text: {
    bold: 'editor-text-bold',
    italic: 'editor-text-italic',
    underline: 'editor-text-underline',
    strikethrough: 'editor-text-strikethrough',
    underlineStrikethrough: 'editor-text-underlineStrikethrough',
  },
  quote: 'editor-quote',
  aligment: {
    left: 'editor-align-left',
    center: 'editor-align-center',
    right: 'editor-align-right',
    justify: 'editor-align-justify',
  },
}

export default PostEditorTheme;